
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/gemini2100/BSupermanSpecs.git'

use_frameworks!

target 'BSupermanUIKit_Example' do
  pod 'BSupermanUIKit', :path => '../'

end
